apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: node-healthcheck-tls
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: auth-proxy
    app.kubernetes.io/name: node-healthcheck-operator
  name: node-healthcheck-auth-proxy
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: node-healthcheck-operator
status:
  loadBalancer: {}
