# This patch modifies the rbac proxy to use TLS config.
# This patch doesn't work in optional/prometheus!
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        args:
          - "--secure-listen-address=0.0.0.0:8443"
          - "--upstream=http://127.0.0.1:8080/"
          - "--tls-cert-file=/app/cert/tls.crt"
          - "--tls-private-key-file=/app/cert/tls.key"
          - "--logtostderr=true"
          - "--v=10"
        volumeMounts:
          - name: tls-config
            mountPath: /app/cert
            readOnly: true
      volumes:
        - name: tls-config
          secret:
            secretName: node-healthcheck-tls
