---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: dummy
  annotations:
    support: Red Hat
spec:
  maintainers:
  - email: team-dragonfly@redhat.com
    name: Dragonfly Team
  provider:
    name: Red Hat
    url: https://www.redhat.com
  links:
    - name: Node Healthcheck Operator
      url: https://access.redhat.com/documentation/en-us/workload_availability_for_red_hat_openshift/DOCS_RHWA_VERSION/html/remediation_fencing_and_maintenance/node-health-check-operator
    - name: Source Code
      url: https://github.com/medik8s/node-healthcheck-operator
